USE cinema2;
SELECT 'USERS' AS tbl, COUNT(*) AS cnt FROM user
UNION ALL SELECT 'ROLES', COUNT(*) FROM role
UNION ALL SELECT 'MOVIES', COUNT(*) FROM movie
UNION ALL SELECT 'BRANCHES', COUNT(*) FROM branch
UNION ALL SELECT 'ROOMS', COUNT(*) FROM room
UNION ALL SELECT 'SEATS', COUNT(*) FROM seat
UNION ALL SELECT 'SCHEDULES', COUNT(*) FROM schedule
UNION ALL SELECT 'BILLS', COUNT(*) FROM bill
UNION ALL SELECT 'TICKETS', COUNT(*) FROM ticket
UNION ALL SELECT 'ARTICLES', COUNT(*) FROM article;
