USE cinema2;

-- Xóa nếu đã có phim cùng tên để tránh trùng lặp
DELETE FROM movie WHERE name IN ('Còi Báo Tử', 'Hộ Linh Tráng Sĩ', 'Ma Tù', 'Chị Chị Em Em 3', 'Trái Tim Quái Thú', 'Digger');

INSERT INTO movie (name, director, actors, categories, duration, release_date, rated, language, is_showing, small_imageurl, large_imageurl, trailerurl, short_description, long_description, created_at)
VALUES
(
    'Còi Báo Tử',
    'Corin Hardy',
    'Dafne Keen, Sophie Nélisse, Sky Yang',
    'Kinh Dị',
    105,
    '2026-08-21',
    'T18',
    'Tiếng Anh - Phụ đề Tiếng Việt',
    0,
    '/img/coi-bao-tu-500_1786683120850.jpg',
    '/img/coi-bao-tu-500_1786683120850.jpg',
    'https://www.youtube.com/watch?v=bkkTCq_utMY',
    'Một nhóm học sinh vô tình nhặt được một cổ vật Aztec bị nguyền rủa mỗi khi tiếng còi ám ảnh ấy cất lên.',
    'Một nhóm học sinh cá biệt vô tình nhặt được một cổ vật Aztec bị nguyền rủa. Mỗi khi tiếng còi ám ảnh ấy cất lên, nó không chỉ xé tan không gian bằng âm thanh rợn người, mà còn đánh thức và triệu hồi chính \"cái chết trong tương lai\" của từng người tìm đến đi săn họ. Liệu nhóm bạn có thể giải mã bí ẩn của lời nguyền trước khi từng người một phải đối mặt với kết cục thảm khốc của chính mình?',
    NOW()
),
(
    'Hộ Linh Tráng Sĩ',
    'Nguyễn Phan Quang Bình',
    'Quách Ngọc Ngoan, Tuấn Trần, Johnny Trí Nguyễn, NSND Tự Long, Hứa Vĩ Văn, Trần Thiên Tú, Đỗ Thị Hải Yến',
    'Hành Động, Tâm Lý',
    118,
    '2026-08-28',
    'T13',
    'Tiếng Việt',
    0,
    '/img/ho-linh-trang-si_1785837646697.jpg',
    '/img/ho-linh-trang-si_1785837646697.jpg',
    'https://www.youtube.com/watch?v=z4VtBgfxawc',
    'Cuối triều Đinh, vua Đinh Tiên Hoàng đột ngột băng hà khiến triều đình rơi vào khủng hoảng.',
    'Cuối triều Đinh, vua Đinh Tiên Hoàng đột ngột băng hà khiến triều đình rơi vào khủng hoảng. Thù trong chưa yên, giặc ngoài đã lăm le xâm lược. Những tử sĩ được giao nhiệm vụ đưa linh cữu nhà vua đến long mạch để an táng. Cuộc hành trình nhiều cam go này trở thành chuyến đi thử thách lòng trung nghĩa...',
    NOW()
),
(
    'Ma Tù',
    'Joko Anwar',
    'Abimana Aryasatya, Almanzo Konoralma, Aming Sugandhi',
    'Kinh Dị',
    110,
    '2026-09-04',
    'T18',
    'Tiếng Indonesia - Phụ đề Tiếng Việt',
    0,
    '/img/ma-tu-500_1786439829483.jpg',
    '/img/ma-tu-500_1786439829483.jpg',
    'https://www.youtube.com/watch?v=n8tqB1CUPQY',
    'Một tù nhân bí ẩn xuất hiện trong một nhà tù khét tiếng bạo lực nhất Indonesia.',
    'Một tù nhân bí ẩn xuất hiện trong một nhà tù khét tiếng bạo lực nhất Indonesia, mang theo một thực thể siêu nhiên chỉ săn lùng những kẻ có năng lượng tiêu cực. Để sống sót, các tù nhân buộc phải cùng nhau làm việc thiện nhằm xóa bỏ bóng tối trong tâm hồn. Hoặc chết từng người một.',
    NOW()
),
(
    'Chị Chị Em Em 3',
    'Nguyễn Hữu Hoàng',
    'Nguyễn Cao Kỳ Duyên, Steven Nguyễn',
    'Tâm Lý, Tình Cảm',
    115,
    '2026-10-16',
    'T18',
    'Tiếng Việt',
    0,
    '/img/chi-chi-em-em-3-500_1786334475431.jpg',
    '/img/chi-chi-em-em-3-500_1786334475431.jpg',
    'https://www.youtube.com/watch?v=-FO53PkM508',
    'Giữa xã hội Bắc Bộ cũ đầy lễ giáo, Thị Mầu – tiểu thư tài sắc nhất vùng bước vào mạng nhện tình cảm rối ren.',
    'Giữa xã hội Bắc Bộ cũ đầy lễ giáo và những khuôn phép khắt khe, Thị Mầu – tiểu thư nổi tiếng tài sắc nhất vùng – bước vào một thế giới nơi tình yêu chưa bao giờ là chuyện của riêng hai người. Những rung động bị che giấu, những mối quan hệ chồng chéo và những lựa chọn trái với khuôn phép tạo nên một mạng nhện tình cảm rối ren.',
    NOW()
),
(
    'Trái Tim Quái Thú',
    'David Ayer',
    'Brad Pitt, J.K. Simmons, Anna Lambe',
    'Hành Động',
    125,
    '2026-09-25',
    'T16',
    'Tiếng Anh - Phụ đề Tiếng Việt',
    0,
    '/img/trai-tim-quai-thu-500_1787041540613.jpg',
    '/img/trai-tim-quai-thu-500_1787041540613.jpg',
    'https://www.youtube.com/watch?v=aw7qSfmlwRk',
    'Sĩ quan James Belmont và chú chó chiến đấu Odin bị mắc kẹt giữa vùng hoang dã Alaska.',
    'Sau một vụ tai nạn máy bay kinh hoàng, sĩ quan Lực lượng Đặc nhiệm James Belmont (Brad Pitt) và chú chó chiến đấu Odin bị mắc kẹt giữa vùng hoang dã sâu thẳm của Alaska. Từ đó, họ buộc phải cùng nhau bước vào cuộc chiến sinh tồn khốc liệt trước thiên nhiên khắc nghiệt.',
    NOW()
),
(
    'Digger',
    'Alejandro González Iñárritu',
    'Tom Cruise, Jesse Plemons, John Goodman',
    'Hài, Giặt Gân',
    120,
    '2026-10-02',
    'T16',
    'Tiếng Anh - Phụ đề Tiếng Việt',
    0,
    '/img/digger-500_1769065542641.jpg',
    '/img/digger-500_1769065542641.jpg',
    'https://www.youtube.com/watch?v=-4fEnppaK5s',
    'Digger. Trò cười rung chuyển cả thế giới. Dự kiến khởi chiếu tháng 10.2026.',
    'Digger. Trò cười rung chuyển cả thế giới. Dự kiến khởi chiếu tháng 10.2026.',
    NOW()
);